### ISSUE TITLE
您好，请教下，怎么做到不限制级数的，根据获取网络去取，有可能4级或者5级？

### ISSUE THREAD

**Issue by SuperSmileForever** [codeliu6572/AddAddress#1]

**Comment by codeliu6572** [comment]
@SuperSmileForever 这个不是写活的，是根据当时需求写的，一般屏幕三个差不多显示满，我理解你意思，应该有街道之类的参数，你只需要在原基础上改几个参数就可以实现你想要的功能了。详情请看封装

**Comment by jiang8121** [comment]
你好  你写的封装非常好 请问在已有地址的情况下 怎么预选中一个地址

**Comment by codeliu6572** [comment]
@jiang8121 这个很简单，你看选中的方法就明白了
